### PR TITLE
Add checkbox state to fix issue

### LINKED ISSUE #132: 'None' Encryption disable  Checkbox of 'Hide password field before printing'
I found this bug

### PR DESCRIPTION
**Pull request by PushpenderSaini0**
Fixes #132 
I add a checkbox state.
```diff
+ hidePassword: network.password.length !== 0 && checkbox
```
this is the main logic used to fix the bug !
### How it works
we want to set `hidePassword` to `false` when we set encryption from `none` --> `WEP/WPA`
for this i check the password length , if it's zero it will suggest we moved from `none` --> `WEP/WPA`

but this logic will set `hidePassword` to `true` when length is not 0 and we move from `WPA` --> `WEP` or other way
hence we also need to add a check if the checkbox is selected or not !

## Preview

demo

### CODE REVIEW

File: src/components/Card.js [hunk 1]
```diff
@@ -145,14 +146,16 @@ export const Card = ({ direction = 'ltr' }) => {
               <input
                 type="checkbox"
                 id="hide-password-checkbox"
+                checked={checkbox}
```
Comment (bndw) [inline src/components/Card.js:149]: It looks like `checkbox` roughly tracks the `network.hidePassword` state. Is it possible to implement this without introducing the new `[checkbox, setCheckbox]` state?

e.g.
```js
checked={network.hidePassword}
```

Comment (PushpenderSaini0) [reply src/components/Card.js:149]: Yes , i will do that !

**Comment by PushpenderSaini0** [comment]
I updated the implementation to use `network.hidePassword` and also re based with master to resolve conflicts.

File: src/components/Card.js [hunk 2]
```diff
@@ -188,7 +190,12 @@ export const Card = ({ direction = 'ltr' }) => {
                   id="encrypt-wpa-wpa2-wpa3"
                   value="WPA"
                   onChange={(e) =>
-                    setNetwork({ ...network, encryptionMode: e.target.value })
+                    setNetwork({
+                      ...network,
+                      encryptionMode: e.target.value,
+                      hidePassword:
```
Comment (bndw) [inline src/components/Card.js:196]: This change isn't necessary

File: src/components/Card.js [hunk 3]
```diff
@@ -199,7 +206,12 @@ export const Card = ({ direction = 'ltr' }) => {
                   id="encrypt-wep"
                   value="WEP"
                   onChange={(e) =>
-                    setNetwork({ ...network, encryptionMode: e.target.value })
+                    setNetwork({
+                      ...network,
+                      encryptionMode: e.target.value,
+                      hidePassword:
```
Comment (bndw) [inline src/components/Card.js:212]: This change isn't necessary

**Review by bndw — CHANGES_REQUESTED** [review]
Hi @PushpenderSaini0 thanks for the patch! I've checked this out locally and while it does resolve the bug, I think the only necessary changes are line adding the `checked` attribute and setting `hidePassword: false` for the None encryption mode.

If you'd remove the changes to line :191 and :202, I'd be happy to merge

**Review by bndw — APPROVED** [review]
